name: ZAP1

on:
  push:
    branches:
      - main

jobs:
  zap_scan1:
    runs-on: ubuntu-latest
    name: OWASP ZAP 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: ZAP Scan 1
        id: step1
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: https://managed-identity-wallets.dev.demo.catena-x.net/
